"""
Pipeline starter-script generator.

The form fields the user fills in (source type + destination + load
mode + primary/cursor key) feed :func:`generate_template`, which
emits a runnable dlt pipeline script. Switching the pipeline to
``code_mode='custom'`` freezes the user's edits; otherwise the
script is regenerated on save.

Kept separate from the executor module so the template machinery is
testable without spinning up the sandbox.
"""

from __future__ import annotations

from typing import Any

# The set of load_mode values is mirrored on the Express side; keep
# in sync if you add modes. Streaming runs the same dlt resource for a
# bounded duration / message count.
LOAD_MODE_TO_DISPOSITION = {
    "replace": "replace",
    "append": "append",
    "merge": "merge",
    "incremental": "append",  # incremental uses dlt.sources.incremental + append
    "streaming": "append",
}


def _safe_ident(s: str) -> str:
    out = "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in (s or ""))
    if not out or out[0].isdigit():
        out = "p_" + out
    return out.lower() or "pipeline"


def generate_template(spec: dict[str, Any]) -> str:
    """Build a starter pipeline script from a structured spec.

    The spec dict mirrors what the UI form collects::

        {
            "name": str, "description": str | None,
            "source_type": "rest_api" | "sql" | "file" | "kafka" | "custom",
            "source_config": {...},          # per-source-type knobs
            "destination": {                  # the resolved destination
                "name": str, "type": str,     # connection type (postgres, snowflake, ...)
                "dataset": str | None,
                "table": str | None,          # for sql/incremental cursor tracking
            },
            "load_mode": str,
            "primary_key": str | None,        # for merge
            "cursor_field": str | None,       # for incremental
        }

    The output is a fully-runnable script; the user can either keep it
    in template mode (regen on every save) or switch to custom mode
    and start editing freely.
    """
    name = _safe_ident(spec.get("name", "pipeline"))
    description = spec.get("description") or "Auto-generated dlt pipeline."
    source_type = spec.get("source_type") or "custom"
    src = spec.get("source_config") or {}
    dest = spec.get("destination") or {}
    load_mode = spec.get("load_mode") or "replace"
    disposition = LOAD_MODE_TO_DISPOSITION.get(load_mode, "replace")
    primary_key = spec.get("primary_key") or ""
    cursor_field = spec.get("cursor_field") or ""
    dataset = dest.get("dataset") or "crunch_pipeline"

    builders = {
        "rest_api": _template_rest_api,
        "sql": _template_sql,
        "file": _template_file,
        "kafka": _template_kafka,
        "custom": _template_custom,
    }
    builder = builders.get(source_type, _template_custom)
    body = builder({
        "name": name,
        "description": description,
        "src": src,
        "dest": dest,
        "load_mode": load_mode,
        "disposition": disposition,
        "primary_key": primary_key,
        "cursor_field": cursor_field,
        "dataset": dataset,
    })
    return body


def _disposition_kwargs(load_mode: str, primary_key: str, cursor_field: str) -> str:
    """Build the kwargs for ``@dlt.resource`` based on load semantics."""
    parts: list[str] = []
    disposition = LOAD_MODE_TO_DISPOSITION.get(load_mode, "replace")
    parts.append(f'write_disposition="{disposition}"')
    if load_mode == "merge" and primary_key:
        keys = [k.strip() for k in primary_key.split(",") if k.strip()]
        if len(keys) == 1:
            parts.append(f'primary_key="{keys[0]}"')
        else:
            parts.append("primary_key=" + repr(keys))
    return ", ".join(parts)


def _pipeline_header(t: dict[str, Any]) -> str:
    dest_type = (t["dest"].get("type") or "duckdb").lower()
    return f'''"""
{t["description"]}

Auto-generated by Crunch — edit freely. Switch the pipeline to
``code_mode=custom`` in the form to stop regen on every save.

Load mode: {t["load_mode"]}   ·   destination: {t["dest"].get("name", "?")} ({dest_type})
"""

import dlt
from typing import Iterator

PIPELINE_NAME = "{t["name"]}"
DATASET = "{t["dataset"]}"

# `ctx` is injected by the Crunch runner — it exposes the resolved
# destination credentials so dlt connects without you re-typing them.
# See ctx.dlt_destination() and ctx.engine for the available hooks.


def _row_count(pipeline, info) -> int:
    """Best-effort row counter — dlt's LoadInfo shape varies across
    versions. We try the trace's normalize-info row_counts first
    (covers dlt 0.4+), fall back to the dataset row-count API, and
    finally to 0 so the script always returns a sensible integer."""
    # dlt 0.4+: pipeline.last_trace.last_normalize_info.row_counts
    try:
        rc = pipeline.last_trace.last_normalize_info.row_counts
        if isinstance(rc, dict) and rc:
            # Skip dlt's internal bookkeeping tables when reporting
            # to the user — they aren't "their" rows.
            return int(sum(
                int(v or 0) for k, v in rc.items() if not str(k).startswith("_dlt_")
            ))
    except Exception:
        pass
    try:
        ds = pipeline.dataset()
        counts = ds.row_counts()
        if isinstance(counts, dict):
            return int(sum(
                int(v or 0) for k, v in counts.items() if not str(k).startswith("_dlt_")
            ))
    except Exception:
        pass
    return 0
'''


def _template_rest_api(t: dict[str, Any]) -> str:
    src = t["src"]
    base_url = src.get("base_url", "https://api.example.com")
    path = src.get("path", "/items")
    auth_header = src.get("auth_header", "")
    cursor_field = t["cursor_field"]

    res_decorator = (
        "@dlt.resource("
        + _disposition_kwargs(t["load_mode"], t["primary_key"], cursor_field)
        + ")"
    )
    newline = "\n"
    quoted_cursor = '"' + cursor_field + '"' if cursor_field else ""
    if t["load_mode"] == "incremental" and cursor_field:
        items_arg = f"cursor = dlt.sources.incremental({quoted_cursor})"
        cursor_init = (
            f"    cursor = dlt.sources.incremental({quoted_cursor}, "
            f"initial_value=None){newline}"
        )
        cursor_apply = (
            f'        params = {{"updated_since": cursor.last_value}} '
            f'if cursor.last_value else {{}}{newline}'
        )
    else:
        items_arg = ""
        cursor_init = ""
        cursor_apply = f'        params = {{}}{newline}'
    auth_line = (
        f'headers["Authorization"] = "{auth_header}"' if auth_header
        else "# headers['Authorization'] = 'Bearer …'"
    )
    return f'''{_pipeline_header(t)}

import requests


{res_decorator}
def items({items_arg}) -> Iterator[dict]:
    """One page-at-a-time HTTP fetch. Customise pagination to fit your API."""
{cursor_init}    url = "{base_url}{path}"
    headers = {{}}
    {auth_line}
    while url:
{cursor_apply}        r = requests.get(url, headers=headers, params=params, timeout=30)
        r.raise_for_status()
        data = r.json()
        # Adjust to your API's envelope:
        records = data.get("results", data) if isinstance(data, dict) else data
        yield from records
        # Pagination — replace with the cursor your API uses.
        url = (data or {{}}).get("next") if isinstance(data, dict) else None


def run() -> dict:
    pipeline = dlt.pipeline(
        pipeline_name=PIPELINE_NAME,
        destination=ctx.dlt_destination(),
        dataset_name=DATASET,
    )
    info = pipeline.run(items())
    return {{"rows_loaded": _row_count(pipeline, info)}}
'''


def _template_sql(t: dict[str, Any]) -> str:
    src = t["src"]
    table = src.get("source_table") or "source_table"
    src_query = src.get("query") or f"SELECT * FROM {table}"
    cursor_field = t["cursor_field"]
    cursor_arg = ""
    if t["load_mode"] == "incremental" and cursor_field:
        cursor_arg = (
            f', incremental=dlt.sources.incremental("{cursor_field}")'
        )

    return f'''{_pipeline_header(t)}

# Replicate from another connection. ``ctx.source_engine`` is set if
# you configured a source connection in the form; otherwise create
# your own SQLAlchemy engine here.

from sqlalchemy import create_engine, text


@dlt.resource({_disposition_kwargs(t["load_mode"], t["primary_key"], t["cursor_field"])})
def rows() -> Iterator[dict]:
    engine = ctx.source_engine or create_engine("{src.get("connection_url", "sqlite:///source.db")}")
    with engine.connect() as conn:
        for r in conn.execute(text("""{src_query}""")):
            yield dict(r._mapping)


def run() -> dict:
    pipeline = dlt.pipeline(
        pipeline_name=PIPELINE_NAME,
        destination=ctx.dlt_destination(),
        dataset_name=DATASET,
    )
    info = pipeline.run(rows(){cursor_arg})
    return {{"rows_loaded": _row_count(pipeline, info)}}
'''


def _template_file(t: dict[str, Any]) -> str:
    src = t["src"]
    pattern = src.get("path", "/data/*.csv")
    return f'''{_pipeline_header(t)}

# File-based pipeline. DuckDB reads the source files (CSV/Parquet/JSON)
# and dlt lands them into the destination connection.

import duckdb


@dlt.resource({_disposition_kwargs(t["load_mode"], t["primary_key"], t["cursor_field"])})
def file_rows() -> Iterator[dict]:
    con = duckdb.connect(":memory:")
    # read_csv_auto / read_parquet pick the right reader by extension.
    cur = con.execute(f"SELECT * FROM read_csv_auto('{pattern}')")
    cols = [d[0] for d in cur.description]
    for row in cur.fetchall():
        yield dict(zip(cols, row))


def run() -> dict:
    pipeline = dlt.pipeline(
        pipeline_name=PIPELINE_NAME,
        destination=ctx.dlt_destination(),
        dataset_name=DATASET,
    )
    info = pipeline.run(file_rows())
    return {{"rows_loaded": _row_count(pipeline, info)}}
'''


def _template_kafka(t: dict[str, Any]) -> str:
    src = t["src"]
    brokers = src.get("brokers", "localhost:9092")
    topic = src.get("topic", "events")
    group = src.get("group_id", "crunch-consumer")
    return f'''{_pipeline_header(t)}

# Streaming consumer. Runs until `ctx.stream_max_seconds` elapses or
# `ctx.stream_max_messages` is hit, whichever first — so the same
# scheduler that runs batch pipelines can drive a bounded streaming
# micro-batch every tick.

import json as _json
import time
from kafka import KafkaConsumer  # pip install kafka-python


@dlt.resource({_disposition_kwargs(t["load_mode"], t["primary_key"], t["cursor_field"])})
def events() -> Iterator[dict]:
    consumer = KafkaConsumer(
        "{topic}",
        bootstrap_servers="{brokers}".split(","),
        group_id="{group}",
        enable_auto_commit=True,
        value_deserializer=lambda b: _json.loads(b.decode("utf-8")),
        consumer_timeout_ms=1000,
    )
    deadline = time.time() + ctx.stream_max_seconds
    seen = 0
    try:
        for msg in consumer:
            yield msg.value
            seen += 1
            if seen >= ctx.stream_max_messages or time.time() >= deadline:
                break
    finally:
        consumer.close()


def run() -> dict:
    pipeline = dlt.pipeline(
        pipeline_name=PIPELINE_NAME,
        destination=ctx.dlt_destination(),
        dataset_name=DATASET,
    )
    info = pipeline.run(events())
    return {{"rows_loaded": _row_count(pipeline, info)}}
'''


def _template_custom(t: dict[str, Any]) -> str:
    return f'''{_pipeline_header(t)}


@dlt.resource({_disposition_kwargs(t["load_mode"], t["primary_key"], t["cursor_field"])})
def my_resource() -> Iterator[dict]:
    """Replace with your data source — yield dicts, dlt does the rest."""
    yield {{"id": 1, "name": "Alice"}}
    yield {{"id": 2, "name": "Bob"}}


def run() -> dict:
    pipeline = dlt.pipeline(
        pipeline_name=PIPELINE_NAME,
        destination=ctx.dlt_destination(),
        dataset_name=DATASET,
    )
    info = pipeline.run(my_resource())
    return {{"rows_loaded": _row_count(pipeline, info)}}
'''
